# Generated by Django 6.0.3 on 2026-03-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["id"]},
        ),
    ]
