# Generated by Django 6.0 on 2026-05-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(fields=["sku"], name="product_var_sku_3f6862_idx"),
        ),
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(fields=["price"], name="product_var_price_cbf06d_idx"),
        ),
        migrations.AddIndex(
            model_name="variant",
            index=models.Index(
                fields=["created_at"], name="product_var_created_b8b124_idx"
            ),
        ),
    ]
