# Generated by Django 6.0.3 on 2026-03-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profileuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="profileuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile/default.png",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
