# Generated by Django 6.0.3 on 2026-03-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profileuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuser",
            name="otp",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="profileuser",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
