# Generated by Django 6.0.3 on 2026-03-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profileuser_otp_profileuser_otp_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuser",
            name="resend_blocked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profileuser",
            name="resend_count",
            field=models.IntegerField(default=0),
        ),
    ]
