# Generated by Django 6.0.3 on 2026-03-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_profileuser_otp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
