# Generated by Django 6.0 on 2026-04-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_profileuser_referral_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuser",
            name="email",
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="profileuser",
            name="full_name",
            field=models.CharField(max_length=60),
        ),
    ]
