# Generated by Django 6.0 on 2026-05-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_profileuser_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otpverification",
            options={},
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("username", models.EmailField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_successful", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="accounts_lo_ip_addr_4f26f9_idx",
                    )
                ],
            },
        ),
    ]
