# Generated by Django 6.0 on 2026-05-02 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_otpverification_options_loginattempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profileuser",
            name="resend_blocked_until",
        ),
        migrations.RemoveField(
            model_name="profileuser",
            name="resend_count",
        ),
        migrations.RemoveField(
            model_name="profileuser",
            name="reset_attempts",
        ),
        migrations.RemoveField(
            model_name="profileuser",
            name="reset_block_until",
        ),
        migrations.RemoveField(
            model_name="profileuser",
            name="reset_requested_at",
        ),
        migrations.RemoveField(
            model_name="profileuser",
            name="reset_token",
        ),
        migrations.CreateModel(
            name="UserSecurity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resend_count", models.IntegerField(default=0)),
                ("resend_blocked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "reset_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reset_requested_at", models.DateTimeField(blank=True, null=True)),
                ("reset_block_until", models.DateTimeField(blank=True, null=True)),
                ("reset_attempts", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Security",
            },
        ),
    ]
