# Generated by Django 6.0 on 2026-05-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_profileuser_resend_blocked_until_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profileuser",
            options={},
        ),
        migrations.AddIndex(
            model_name="profileuser",
            index=models.Index(fields=["email"], name="accounts_pr_email_dd5b7d_idx"),
        ),
        migrations.AddIndex(
            model_name="profileuser",
            index=models.Index(
                fields=["created_at"], name="accounts_pr_created_01704e_idx"
            ),
        ),
    ]
