# Generated by Django 6.0.3 on 2026-04-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("return", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
