# Generated by Django 6.0.3 on 2026-04-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
