# Generated by Django 6.0.3 on 2026-04-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_orderitem_cancel_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURN_REQUESTED", "Return Requested"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
