# Generated by Django 6.0.3 on 2026-04-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_orderitem_item_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("RAZORPAY", "Razorpay")],
                default="COD",
                max_length=20,
            ),
        ),
    ]
